# Performance Optimization Configuration
# ====================================

# Horizon testing configuration
horizon_test:
  normalize: "global"
  decay: ["exp", 0.7]
  mask: "letters"

# Decay function testing
decay_test:
  horizon: 5
  normalize: "global"
  mask: "letters"

# Batch optimization settings
batch_optimization:
  horizon: 3
  normalize: "global"
  decay: ["exp", 0.8]
  mask: "letters"

# Memory analysis settings
memory_analysis:
  horizon: 4
  normalize: "row"
  decay: ["gauss", {'mu': 2.0, 'sigma': 1.0}]
  mask: "letters"

# Fast algorithm (optimized for speed)
fast_algorithm:
  horizon: 2
  normalize: "global"
  decay: ["exp", 1.0]
  mask: "letters"

# Balanced algorithm (speed vs accuracy)
balanced_algorithm:
  horizon: 4
  normalize: "row"
  decay: ["gauss", {'mu': 2.0, 'sigma': 1.0}]
  mask: "letters"

# Accurate algorithm (optimized for precision)
accurate_algorithm:
  horizon: 8
  normalize: "global"
  decay: ["morlet", {'omega': 3.0, 'sigma': 1.2}]
  mask: "letters"

# Complex algorithm (advanced features)
complex_algorithm:
  horizon: 6
  normalize: "row"
  bank: "morlet:omega=3.0;sigma=1.0 + gauss:mu=2.5;sigma=1.5"
  aggregate: "sum_abs"
  mask: "letters"

# Reference algorithm (baseline for comparison)
reference_algorithm:
  horizon: 5
  normalize: "global"
  decay: ["gauss", {'mu': 2.5, 'sigma': 1.2}]
  mask: "letters"

# Minimal resource usage
minimal_resources:
  horizon: 1
  normalize: "global"
  decay: ["exp", 2.0]
  mask: "none"

# Maximum performance
maximum_performance:
  horizon: 15
  normalize: "row"
  bank: "morlet:omega=2.0;sigma=1.0 + morlet:omega=4.0;sigma=1.5 + gauss:mu=3.0;sigma=2.0"
  aggregate: "sum_abs"
  mask: "letters"
  phase: ["entropy", 0.1, 3.1415]