# Wavelet Analysis Configuration
# =============================

# Basic wavelet settings
basic_wavelet:
  horizon: 8
  normalize: "global"
  decay: ["morlet", {'omega': 3.0, 'sigma': 1.0}]

# Advanced multi-kernel analysis
multi_kernel:
  horizon: 10
  normalize: "row"
  bank: "morlet:omega=2.0,sigma=1.0 + mexican:sigma=1.5 + gauss:mu=3.0,sigma=2.0"
  aggregate: "sum_abs"

# Complex phase analysis
phase_analysis:
  horizon: 6
  normalize: "global"
  decay: ["morlet", {'omega': 4.0, 'sigma': 1.2}]
  phase: ["entropy", 0.1, 3.1415]

# High-resolution analysis
high_resolution:
  horizon: 15
  normalize: "row"
  bank: "morlet:omega=1.0,sigma=0.8 + morlet:omega=3.0,sigma=1.2 + morlet:omega=6.0,sigma=1.8"
  aggregate: "sum_abs"

# Research-grade settings
research:
  horizon: 20
  normalize: "global"
  bank: "morlet:omega=2.0,sigma=1.0,scale=0.8 + morlet:omega=4.0,sigma=1.5,scale=1.2 + mexican:sigma=2.0,scale=1.0"
  aggregate: "sum_abs"
  phase: ["theta", 0.7854]  # Ï€/4

# Performance-optimized
performance:
  horizon: 5
  normalize: "global"
  decay: ["morlet", {'omega': 3.0, 'sigma': 1.0}]